### ISSUE TITLE
What's the best restaurant you've ever eaten at?

### ISSUE THREAD

**Issue by una** [csswizardry/ama#1]
You can name a top 3 if you can't decide on one 🍖

**Comment by csswizardry** [comment]
There is absolutely no way I can answer this completely honestly because I’ve eaten at hundreds of restaurants. Food is a huge part of my life, and I’m incredibly fortunate that I get to sample a lot of it as I travel. However, if I had to pick a top three, from the top of my head:

1. [**4Leoni**](http://4leoni-firenze.ch/en/), Zürich
  A few days after you and I hung out at Frontend Conf in Zürich, my friends Eros and Manuela took me to an amazing Italian restaurant. They both grew up in the Italian-speaking part of Switzerland, so spoke to the owner and managed to get us an off-menu feast put together. One of the best steaks I ever had. They let us choose which one we wanted:
  ![Steak!](http://i.imgur.com/JEM7zN3.jpg)
  As well as steak there was pasta, antipasti, meatballs, wine… Oh it was goooood!
2. [**House of Tides**](http://houseoftides.co.uk/), Newcastle, UK
  I used to live about 500m from this Michelin Starred restaurant. It was the first meal I had where I was truly happy to be eating fish.
3. [**Roux at the Landau**](http://rouxatthelandau.com/), London, UK
  I had the tasting menu with wine pairing here. It was amazing, and an all-round enjoyable evening.

As soon as I answer this, I _know_ I’ll think of about ten others :(
