### ISSUE TITLE
Do you have a naming convention for size variables?

### ISSUE THREAD

**Issue by mikeriley131** [csswizardry/ama#10]
For example, with media queries:

```
$brk-small-width: 30em;
$brk-med-width: 45em;
$brk-large-width: 60em;
$brk-xlarge-width: 75em;

@mixin brk-small {
  @media screen and (min-width: $brk-small-width) {
    @content;
  }
}

@mixin brk-med {
  @media screen and (min-width: $brk-med-width) {
    @content;
  }
}

@mixin brk-large {
  @media screen and (min-width: $brk-large-width) {
    @content;
  }
}

@mixin brk-xlarge {
  @media screen and (min-width: $brk-xlarge-width) {
    @content;
  }
}
```

This becomes problematic when introducing a new MQ between small and medium, or between medium and large. What is your preferred approach?

**Comment by csswizardry** [comment]
I have a bit of an annoying answer for you:

Needing to slide a new breakpoint in between medium and large (for example) represents some design debt (which absolutely is a thing), so I would argue that the solution here doesn’t exist in code, but in the design. Go back a step and see what needs reevaluating and try to solve it there. Taking this approach in general will solve a lot of these kinds of issues (17 different font-sizes, 19 styles of button, etc.).

I think my key point here is that **design debt is separate to technical debt**. A lot of these issues get noticed in the development phase, so they’re just referred to as tech debt, and it’s assumed that it’s the developers job to tidy up, solve, or fix. It’s not: you need to go back a step and pay off some design debt :)

Another tip. Instead of:

```scss
$brk-small-width: 30em;
$brk-med-width: 45em;
$brk-large-width: 60em;
$brk-xlarge-width: 75em;
```

…write them like:

```scss
$brk-width-small: 30em;
$brk-width-med: 45em;
$brk-width-large: 60em;
$brk-width-xlarge: 75em;
```

This drilldown approach will work nicer with your autocomplete.
