### ISSUE TITLE
What do you miss about the good old days?

### ISSUE THREAD

**Issue by davewallace** [csswizardry/ama#14]
Go on, what do you miss, I'm sure between everyone that comments on this issue and your own observations and contributions we'll collect some gems!

[Dave](https://twitter.com/HandleTheJandle)

**Comment by csswizardry** [comment]
Honestly, between IE6 bugs, competing box-models, lack of support for transparent PNGs, Flash, very rudimentary versions of HTTP, and goodness knows whatever else I’ve managed to scrub from my mind, there isn’t that much to miss!

Right now we’re dealing with HTTP/2, almost ubiquitous HTTPS, heavily standardised browsers, huge OSS efforts from almost all large tech companies, ServiceWorker and PWAs giving native a run for its money; the web is really starting to win!

But, I should really answer your question. I guess I miss:

* **Creativity:** I used to trawl CSS gallery sites for hours on end (remember those?!), but now almost every site ever almost looks identical. CSS used to be such a creative outlet for so many people, and now we have more power than ever at our fingertips and we’re all using to build the same looking websites.
* **Hacks and fixes:** In a weirdly perverse kind of way, I really miss the creative ingenuity that people used to have to employ in order to achieve things in CSS (or any of the platform for that matter). The simultaneously elegant but insane workarounds that were testament to a) the state of the web at that time and b) the creativity of the minds building for it. The web has now become much more about engineering challenges which are a bunch of fun in a different way, but I definitely miss when our largest challenges were getting round corners working on your nav (sliding doors, anyone?).
* **The simplicity:** When I was starting out, a new project was as simple as copying and pasting your last `index.html` into a new folder on your computer, downloading the Meyer reset, and getting to work. I started a new UI build for a client the other day, and we’re creating a UI toolkit for their entire front-end. The setup process requires a multitude of different tools and packages, dependencies, CLI knowledge, you name it. It currently builds 76KB of CSS, yet the `node_modules` directory weighs over 32MB. I totally appreciate that the web is a lot more complex now, and that our tooling is a lot more sophisticated, but there’s a large part of me that still believes that `float: left` should not be so difficult to achieve.

There might be more, but I would absolutely say that on the whole, the web is better now than it was back then.

**Comment by davewallace** [comment]
Thanks @csswizardry :)

Some of the IE6 PNG fixes were awesome. I never quite managed to perfectly nail the bottom right rounded corner of an expandable box using PNG's and their scale modes in the filter hack - a touch a JS to think about heights was required if I remember correctly... time to let that one go I think!

I know what you mean about creativity in design also, CSS Zen garden was fantastic for inspiration  - and convincing people investing in my time to work with CSS for them was worth it. I guess skeuomorphic designs pop up now and then for me to implement, to keep things entertaining, otherwise it does seem like material design & boostrapery always get to a point where there's no more $$ or time left to take it beyond where those ways of thinking get a product to initially.

**Comment by kimblim** [comment]
> **The simplicity**

Oh yes! Couldn't agree more — it seems like setting up a simple site these days requires node, gulp, scss, git etc.; often for no reason other than "tooling". That's also why, when I need to do some quick, experimental work, I turn to an online editor (my choice is CodePen, but could be JSFiddle or one of the others). No setup, it's just "go and do". 

I guess it compares to visual designers grabbing a pen and pad before opening some software. CodePen is my pen and pad, where I can mess about with no consequenses.

**Comment by csswizardry** [comment]
> That's also why, when I need to do some quick, experimental work, I turn to an online editor…

Exactly! You don’t want any setup to get in the way of your moment of inspiration/creativity.
