### ISSUE TITLE
Who inspires you in a professional sense?

### ISSUE THREAD

**Issue by BenjaminRCooper** [csswizardry/ama#17]
and why.

**Comment by csswizardry** [comment]
This is so difficult to answer haha. I think everyone has something amazing and inspiring to contribute (the hard part is finding it all!) but I guess people that I consistently look to include:

* [Jake Archibald](https://twitter.com/jaffathecake): He just knows a lot about a lot, and he’s super mellow about it.
* [Ilya Grigorik](https://twitter.com/igrigorik): His HPBN book is unreal. Such a great read.
* [Rachel Andrew](https://twitter.com/rachelandrew): She’s prolific! Never known anyone work so tirelessly.
* [Jeremy Keith](https://twitter.com/adactio): His insight and wisdom is as valuable today as it has been since he started (if not more so).

There are more, but it’s just so hard to think of people on the spot!

**Comment by BenjaminRCooper** [comment]
Great answers mate. You have named all I would mention, but I also think all members of the Chrome team are amazing in terms of knowledge in an extremely difficult section that is performance.
