### ISSUE TITLE
Given the increasing complexity of the web, where would you recommend beginners start?

### ISSUE THREAD

**Issue by ShaneHudson** [csswizardry/ama#21]

**Comment by csswizardry** [comment]
Oh man! I like this one!

Well, I would actually say (with the benefit of almost a decade of hindsight) start off by learning about the web as a platform. Learn about its philosophy, its fragility, its nuance. Learn about HTTP, about TCP/IP, and how the network actually works.

We spend most of our time working in a layer of abstraction (and every new framework only serves to exacerbate this), so having a working knowledge of the fundamentals will help to make sense of and distil everything that happens on top of it.

Honestly—and again, with hindsight—I think one of the most eye-opening things I ever learned wasn’t Sass or Git or any tool, but it was how the internet worked.

From there, look at HTML. HTML is the single most important language on the internet, and anything/everything is a bonus. Understand HTML, and the rest can follow.

To answer from the other side of the argument, I would absolutely **not** recommend that anyone start by ‘Learning React’ or ‘Learning WordPress’, because that is far too far removed from the platform.

Fundamentals first; the rest can follow.
