### ISSUE TITLE
Performance consultant: How do you find jobs, and would you advise it as a career path?

### ISSUE THREAD

**Issue by mendaomn** [csswizardry/ama#27]
Hi Harry,

I have started recently my own career as a web developer and consultant. I would love to offer my services as a "performance consultant", meaning I would like to perform audits and, possibly, either solving the issues, or offer training for the team working on it.

- Would you advise it as a career path? Does it "work", in your opinion, or is there not enough performance culture in companies?
- How do you find jobs like this? Do companies reach out to you, or do you offer some kind of free "unsolicited audit", that the prospect can appreciate?
- Would you need help with doing things? I could use some mentorship on the topic, and I believe my skills in terms of performance could be of help

I apologize if this comes out as too blunt or barefaced, I am not a native English speaker (and I totally looked barefaced up)

Have a nice day!

**Comment by csswizardry** [comment]
Hey!

> I have started recently my own career as a web developer and consultant.

Congratulations! I hope you enjoy it, and that it treats you well :)

> I apologize if this comes out as too blunt or barefaced…

Not at all—this is an ask me _anything_, remember ;)

> Would you advise it as a career path?

This depends on so much context, I’m afraid. If you like travel, have demonstrable skills, a good audience, are good at lead generation, then yes! If not, then your mileage may vary. To answer slightly differently: I do enjoy it because it is possible.

> Does it "work", in your opinion…

It’s important to note that the majority of my career has actually been as a CSS Architecture consultant, and the strong performance focus is relatively new (I’ve always done performance work, but [only recently](https://csswizardry.com/2017/01/a-new-year-a-new-focus/) have I started making it front-and-centre). It absolutely does/can work, but you have to be able to constantly/consistently find new clients, you need a broad reach, and you have to specialise. A lot. This means that to cater to the consultancy market you kind of have to move away from the traditional development market a little. Specialist over generalist.

> …or is there not enough performance culture in companies?

A lack of performance culture means that there’s actually even more of a market to break into! If everyone was doing this already then there’d be less need for people like me to help out with it. ([Relevant XKCD.](https://xkcd.com/1053/))

> How do you find jobs like this? Do companies reach out to you, or do you offer some kind of free "unsolicited audit", that the prospect can appreciate?

I’m very fortunate that I have quite a large presence/audience that I’ve spent the last decade (seriously) building up. Because of this, people reach out to me. It took a _lot_ of groundwork, but it means that I already have something of a reputation which does end up bringing people to me.

Without this, I would probably do speculative audits, cold introductions, or partner with others offering similar and try to piggyback the foundations they’ve already laid.

> Would you need help with doing things? I could use some mentorship on the topic, and I believe my skills in terms of performance could be of help

I’m afraid that the answer here has to be a ‘not really’. I wish I could answer differently, but the way I run my business is currently very much _not_ suited to having more than one person (lack of time on my part; lack of routine for employees/mentees). That said, my inbox (or this AMA repo) is always open to answer questions about careers and mentoring etc.

Thanks!
H
