### ISSUE TITLE
How did you manage your skills/career from junior dev to Developer expert?

### ISSUE THREAD

**Issue by tongrhj** [csswizardry/ama#33]
I'm curious about your personal journey from school to Google Developer expert. In [a previous question](https://github.com/csswizardry/ama/issues/7) (and from stalking your linkedin) you joked that you learnt from the school of life, so I'm presuming you didn't have a Computer Science (CS) degree.

On that assumption, how did you learn and grow as a developer? Did you feel disadvantaged because of a lack of CS education?

I graduated from a coding bootcamp, and have been working at a startup for a year as a frontend web developer since then. Advice from someone at your stage of success would be much appreciated, and I'd like to pass it on to people worried about not having a CS background when deciding whether to kickstart their career in programming.

**Comment by csswizardry** [comment]
Hey!

> …so I'm presuming you didn't have a Computer Science (CS) degree.

You’re correct. But I actually don’t have any degree of any kind at all. I feel that there’s a lot less focus on higher education in tech here in the UK than a lot of other places.

> …how did you learn and grow as a developer?

* **Sheer enthusiasm:** it helps to love what you’re learning;
* **Structure:** I didn’t spread myself too thin by trying to learn too much—a mistake I see a lot of developers making;
* **Fascination:** I find almost everything at least superficially interesting, so there are subjects outside of my remit that I will learn about and borrow from;
* **Osmosis:** Surround yourself by people from different disciplines, different backgrounds, different skill levels;
* **Focus on the fundamentals:** We always work on abstractions above our actual medium, so we’re often shielded a little too much—explore the underlying principles and your eyes will be opened;
* **Time:** I’ve been doing this for about ten years now. That helps.

> Did you feel disadvantaged because of a lack of CS education?

Absolutely not. I have never been asked about any of my qualifications (their existence and/or their value), only about my background, skills, and approaches. Again, this may be somewhat unique to the UK.

> Advice from someone at your stage of success would be much appreciated…

A lot of the best developers I’ve worked with haven’t been the best **because of** their coding skills, but rather for their organisational skills, their general troubleshooting abilities, their ability to pull together a team of people greater than the sum of their parts, and able to talk to non-technical stakeholders. For me, the biggest part of being a senior developer isn’t about knowing the most languages, it’s about a much more holistic approach to solving a problem.

So what I would try and do is shadow as many people in your startup as you can. Sit in on DevOps meetings—even if most of it goes straight over your head, you’ll pick up little bits and pieces of knowledge that your colleagues might miss. This is the osmosis thing. Go and shadow customer support for a while; learn about what your users are actually struggling with. Doing this will expose you to more of the company, which is valuable in and of itself, but will also make you friends (allies) throughout the business that you can call on when you might need help.

None of that requires a CS degree—it just takes motivation, intuition, and diligence.

Have fun!

**Comment by igor-anosov** [comment]
Awesome!!! Good advises! :)
