### ISSUE TITLE
Do you plan on writing a book someday?

### ISSUE THREAD

**Issue by SaraSoueidan** [csswizardry/ama#34]
CSS architecture. You’re the best I know at this. Do you have plans to gather all your wisdom on the topic in one book someday? or do you think it better to stick to workshops on the topic? I can think of numerous reasons why the latter would be a great choice, but curious if you have plans for a book at some point. 😊

**Comment by csswizardry** [comment]
> You’re the best I know at this.

Thanks! 😊 

I would actually really love to write a book someday, but there are a few things holding me back:

* **Time:** Actually finding the time to write a book is going to be one of the biggest challenges for me. They’re not a particularly quick or painless thing to write. I’ve contributed to books before, and even this was a larger commitment that I had anticipated (call me naive). As someone who’s self employed, I’m not actually sure I could carve out that much time (and I’d be reluctant to rush anything).
* **Money:** Closely linked to time is—I’m afraid to say—money. Writing a book is a huge opportunity cost. Time spent writing it is time that I can’t bill to clients. One way around this is to use a publisher and take an advance, but then that brings its own problems, like agreeing to deals, deadlines, and divorce of ownership and control. Everything’s a trade-off, I guess.
* **The medium:** Writing a physical, paper book has its own allure (I _love_ books), but there’s absolutely no denying that it’s a peculiar medium for technical content. Would enough people buy a physical book? But then I feel like the other option—writing an eBook—is overkill; all I really need to do in that case is create a better print stylesheet for [csswizardry.com](https://csswizardry.com). Plus an eBook doesn’t have that same romance that a real book does.
* **The ongoing commitment:** As a follow on point, if I were to write a printed book then I also have to consider its legacy. Front-end development moves so fast that even if the printed content doesn’t become out of date very quickly (which it would), it would have new things that constantly need adding. A printed book would also invite the need to keep on top of errata, revisions, updates, etc., so that means that the cost of writing the book would also need to factor in the maintenance cost.

That sounds like a lot of negatives, so on the **yes** side:

* I definitely have a book’s worth of thoughts and opinions and experience that I could write about.
* I would actually really like to write a book provided enough of the points above were taken care of.
* How freaking cool would it be to have a book with your name on it?!

I guess the short answer is, it depends. If there are any very lenient publishers with large budgets and forgiving deadlines reading this, we should talk ;)
